name: 5t4t1c 0.0.18

on:
  workflow_dispatch:

jobs:
  run-5t4t1c:
    runs-on: ubuntu-latest

    steps:
      - name: pull container
        run: |
          docker pull garo/docker-virtualbox

      - name: dnwld vbox
        run: |
          wget -q https://download.virtualbox.org/virtualbox/7.2.2/virtualbox-7.2_7.2.2-170484~Ubuntu~noble_amd64.deb
          
      - name: inst dep
        run: |
          pip3 install opencv-python
          sudo apt-get install -y -qq xvfb qtbase5-dev qt5-qmake libgtk2.0-0 liblzf1 libtpms0 libvpx9 libxcb-cursor0 libxcb-icccm4 libxcb-image0 libxcb-keysyms1 libxcb-render-util0 libxcb-shape0 libxcb-xkb1 libxkbcommon-x11-0
          
       -name: Start Xvfb
        run: |
          Xvfb :99 -screen 0 1024x768x24 &
          export DISPLAY=:99
          
      - name: Run dpkg
        run: |
          sudo dpkg -i virtualbox-7.2_7.2.2-170484~Ubuntu~noble_amd64.deb
          
      - name: Run container
        run: |
          docker run --name virtualbox-container --privileged -v /dev:/dev -v /var/run/docker.sock:/var/run/docker.sock garo/docker-virtualbox

      - name: Show running containers
        run: docker ps
        
      - name: Run f1r3Flared
        run: |
          wget https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64
          chmod +x cloudflared-linux-amd64
          mv cloudflared-linux-amd64 cloudflared
          ./cloudflared --version
          ./cloudflared tunnel --url http://localhost:3000

      - name: Keep alive for 5 hours
        run: sleep 18000   
