name: Upload to Repository

permissions:
  contents: write

on:
  workflow_dispatch:
  push:
    paths:
      - Hide.me-Setup-4.3.1.exe

jobs:
  upload-installer:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download
        run: |
          curl -L "https://hide.me/downloads/Hide.me-Setup-4.3.1.exe" -o Hide.me-Setup-4.3.1.exe

      - name: Add file
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add Hide.me-Setup-4.3.1.exe
          git commit -m "Add Hide.me-Setup-4.3.1.exe" || echo "No changes to commit"
          git push origin HEAD:${{ github.ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
